name: Calculator API CI/CD

on:
  push:
    branches: ['**']

jobs:
  CI:
    name: "CI"
    uses: ./.github/workflows/ci.yml
  
  CD:
    name: "CD"
    needs: ['CI']
    uses: ./.github/workflows/cd.yml